ryusei1124/RIZAKAWA

db/migrate/20191108002211_add_user_information__to_users.rb
db/schema.rb

userテーブルのカラムをログイン保持カラム以外追加

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/models/user.rb
app/views/shared/_error_messages.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/locales/ja.yml
config/locales/models/models_ja.yml
db/migrate/20191108021721_add_fix_to_users.rb
db/migrate/20191108074435_change_data_fix_day_to_users.rb
db/schema.rb

生徒登録画面(形のみ)

---

app/models/notice.rb
app/models/user.rb
db/migrate/20200215121131_create_notices.rb
db/schema.rb
db/seeds.rb
test/fixtures/notices.yml
test/models/notice_test.rb

お知らせ用モデルとカラムの作成をしました。とりあえず、ER図通りに
users対notices　1対多　1対1　としてあります。
レビューお願いします。

お知らせ用モデルとカラムの作成

---

app/assets/stylesheets/notices.scss
app/controllers/notices_controller.rb
app/models/notice.rb
app/models/user.rb
app/views/notices/_notice_form.html.erb
app/views/notices/index.html.erb
app/views/notices/new.html.erb
app/views/shared/_error_messages_notice.html.erb

お知らせ一覧ページに3点 機能修正、追加しました。
1.「お知らせタイトル」「お知らせ内容」空欄バリデーション追加
2.表の横サイズ70%に修正
3.表の位置を真ん中に修正
レビューお願いします。

4_2お知らせ投稿ページ作成_add

---

app/models/lesson.rb
app/models/reservation.rb
db/migrate/20200216084635_create_lessons.rb
db/migrate/20200216085211_create_reservations.rb
db/schema.rb
test/fixtures/lessons.yml
test/fixtures/reservations.yml
test/models/lesson_test.rb
test/models/reservation_test.rb

・Lessonモデル作成
・Reservationモデル作成
内容は仕様書の通り
https://docs.google.com/spreadsheets/d/1KMGJjr0cqAyV0K0IW9gKJpnX5DK-YI13cIMDjaEC1p8/edit#gid=0
モデル作成のみです

5 3 lesson add

---

app/controllers/users_controller.rb
app/views/users/index.html.erb

12 1 user add

---

app/assets/stylesheets/notices.scss
app/views/notices/show.html.erb

お知らせ詳細ページ左寄せ
管理者権限詳細ページ遷移バックグランド修正
レビューお願いします。

16 2 notice edit

---

app/assets/javascripts/reservations.coffee
app/controllers/application_controller.rb
app/controllers/attendances_controller.rb
app/controllers/lessons_controller.rb
app/controllers/reservations_controller.rb
app/controllers/sessions_controller.rb
app/helpers/application_helper.rb
app/helpers/reservations_helper.rb
app/models/student.rb
app/views/lessons/weeklyschedule.html.erb
app/views/reservations/useredit.html.erb
config/routes.rb
test/controllers/reservations_controller_test.rb

・管理者新規登録時重複エラーがでるようにする
・受講生側での登録修正　ZOOM リアル変更機能
（一般ユーザーでログインして週間予定から予約済分のみリンクでいける）

20-4ユーザー側の予約詳細画面_add

---

app/controllers/users_controller.rb
app/mailers/application_mailer.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/send_mail.html.erb
app/views/user_mailer/send_mail.text.erb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
test/mailers/previews/user_mailer_preview.rb
test/mailers/user_mailer_test.rb

生徒登録時にメール送信機能を実装しました
herokuにデプロイしてメールの送信を確認したいのでレビューよろしくお願いします。

24 user edit

---

app/controllers/users_controller.rb
app/views/users/_edit_basic_info.html.erb
app/views/users/index.html.erb

モーダル表示がうまくいかず詰まっております。
助力いただきたいです。
行ったこと
・edit_basic_info.js　の修正
・users.controllerに　before action追加（新しくメソッド追加）

モーダル表示がうまくいかない

---

app/models/answer.rb
app/models/question.rb
app/views/reservationusers/useredit.html.erb
db/migrate/20200409064415_create_questions.rb
db/migrate/20200409065200_create_answers.rb
db/schema.rb
test/fixtures/answers.yml
test/fixtures/questions.yml
test/models/answer_test.rb
test/models/question_test.rb

お問い合わせテーブル作成
回答テーブル作成
ユーザー側予約管理画面見た目修正

38_5生徒からの問い合わせ機能_add

---

app/controllers/lessons_controller.rb
app/controllers/reservations_controller.rb
app/views/layouts/_header.html.erb
app/views/lessons/lesson_detail.html.erb
app/views/notices/edit.html.erb
config/routes.rb

一旦プルリクします。
1. 予約履歴ページ作成&ヘッダーから遷移実装（バックエンドまだ）
2. 出欠ボタン機能実装中
レビューお願いします。

36_4予約詳細・出欠管理ページバックエンド実装_add

---

app/controllers/lessoncomments_controller.rb
app/controllers/lessons_controller.rb
app/controllers/notices_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/notices/index.html.erb
app/views/reservationusers/useredit.html.erb
app/views/user_mailer/send_mail.html.erb
db/seeds.rb

お知らせ情報が投稿されたら契約中の保護者全員にお知らせ情報のメールがおくれるようにしました。
授業登録した場合の自動登録の設定に誤りあり、修正しました。

 41_1メールシステム再構築_add

---

app/controllers/reservationusers_controller.rb
app/views/reservationusers/_methodchange.html.erb
app/views/reservationusers/_transfer.html.erb
app/views/reservationusers/useredit.html.erb
db/migrate/20200417083434_add_details_to_students.rb
db/schema.rb

・先生備忘録用に生徒備考をモデルに追加。ユーザー用予約詳細（管理者兼用）に表示させることを考えています。
・ユーザー側予約詳細もリファクタリングしてモーダルを外部ファイルにしました。

42_1生徒情報備考追加_add

---

app/assets/javascripts/reservations_log.coffee
app/assets/stylesheets/reservation_logs.scss
app/controllers/lessoncomments_controller.rb
app/controllers/lessons_controller.rb
app/controllers/reservation_logs_controller.rb
app/helpers/application_helper.rb
app/helpers/reservations_log_helper.rb
app/models/reservation.rb
app/views/layouts/_header.html.erb
app/views/reservation_logs/index.html.erb
app/views/reservations/reservations_log.html.erb
app/views/reservationusers/useredit.html.erb
config/routes.rb
test/controllers/reservations_log_controller_test.rb

46_4授業予約履歴情報作成_add

---

app/controllers/lessons_controller.rb
app/controllers/reservation_logs_controller.rb
app/controllers/reservations_controller.rb
app/controllers/reservationusers_controller.rb
app/helpers/application_helper.rb
app/views/lessons/_add_student.html.erb
app/views/lessons/lesson_detail.html.erb
app/views/lessons/weeklyschedule.html.erb
app/views/notices/_basicstudent.html.erb
app/views/notices/index.html.erb
app/views/reservation_logs/index.html.erb
app/views/reservationusers/_methodchange.html.erb
app/views/reservationusers/_student.html.erb
app/views/reservationusers/reservationnewuser.html.erb
app/views/reservationusers/useredit.html.erb
config/routes.rb
db/seeds.rb

管理者側画面から生徒授業予約
キャンセル待ち機能修正
週間予定表にキャンセル待ちの場合独自色設定（ピンク）
他リファクタリングしました。

49_4管理者授業予約_add

---

app/assets/stylesheets/reservations.scss
app/controllers/lessons_controller.rb
app/views/lessons/lesson_detail.html.erb

予約詳細・出欠管理ページについて
1.　タイトル２段目と３段目の項目覧を対象がいなければ「非表示」+「対象がいないことを示すメッセージ」を表示実装しました。
レビューお願いします。

53_生徒欄とキャンセル待ち欄の項目動的表示機能実装_edit

---

app/controllers/lessoncomments_controller.rb
app/controllers/lessons_controller.rb
app/controllers/reservations_controller.rb
app/controllers/reservationusers_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/lessons/weeklyschedule.html.erb
app/views/reservationusers/reservationnewuser.html.erb
app/views/reservationusers/useredit.html.erb

・生徒が予約新規や取消登録したら先生にメールが届くようにした
・先生が生徒に送付したメールのｂｃｃが先生に届くようにした
・メール機能のプログラム整備（ダブり記載回避等）
・週間予定の授業の色合い修正
　未来・過去にかかわらず予約済　薄緑　予約してないもの黄色　キャン待ち:ピンク　取消:青緑色 に統一した　

56_1メール機能追加（生徒入力情報関連）_add

---

app/assets/stylesheets/users.scss
app/controllers/lessons_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/views/lessons/lesson_detail.html.erb
app/views/notices/_notice_form.html.erb
app/views/users/new.html.erb
config/locales/models/models_ja.yml

管理者側の生徒新規登録フォーム
1.　アコーディオン実装
2.　日本語表示設定
3.　フォーマット調整
4.　必須マーク実装
予約生徒・修正&出欠管理 欄
1.　名前（学年）表示実装
必須項目整備後は未確認ですが、一旦プルリクします。
レビューお願いします。

54 1 student add

---

app/assets/stylesheets/lessons.css
app/assets/stylesheets/reservations.scss
app/views/lessons/lesson_detail.html.erb
app/views/notices/index.html.erb
app/views/notices/show.html.erb

件名【予約詳細ページ　レスポンシブフォーマット変更】
以下　実装しました。
1.　time-fieldがスマホで見ると横長になってしまうバグ修正完了
2.　セル内上下中央揃え完了
レビューお願いします。

59_4予約詳細ページ　レスポンシブフォーマット変更_edit

---

config/environments/production.rb

69_サブheroku追加_add

---

app/controllers/lessons_controller.rb
app/controllers/users_controller.rb
app/views/lessons/lesson_detail.html.erb
app/views/students/_students_time.html.erb
app/views/users/index.html.erb

新規受講生登録時、他受講生の固定時間が確認しやすいように一覧表を作成した

78_1生徒固定時間一覧表モーダル追加_edit
